from reportlab.lib import colors
from reportlab.lib.pagesizes import A4, landscape
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_CENTER
from io import BytesIO
from django.core.files import File
from datetime import datetime


class InvoicePDFGenerator:

    @staticmethod
    def generate(invoice, transactions, report_type, period_label):
        buffer = BytesIO()
        
        # Use landscape for more columns if needed
        doc = SimpleDocTemplate(buffer, pagesize=A4, topMargin=40, bottomMargin=40)
        styles = getSampleStyleSheet()
        
        # Create custom styles
        title_style = ParagraphStyle(
            'CustomTitle',
            parent=styles['Title'],
            alignment=TA_CENTER,
            fontSize=16,
            textColor=colors.HexColor('#1a237e')
        )
        
        elems = []

        # Header
        elems.append(Paragraph("<b>AIRPORT FUEL MANAGEMENT SYSTEM</b>", title_style))
        elems.append(Spacer(1, 6))
        
        type_label = "Daily Invoice" if report_type == 'daily' else "Monthly Invoice"
        company_label = invoice.supplier.company_name if invoice.supplier else "All Companies"

        elems.append(Paragraph(f"<b>{type_label} — {period_label}</b>", styles['Heading2']))
        elems.append(Spacer(1, 16))

        # Meta table
        meta_data = [
            ["Invoice Number:", invoice.invoice_number],
            ["Report Type:", type_label],
            ["Period:", period_label],
            ["Company:", company_label],
            ["Generated By:", invoice.generated_by.get_full_name() or invoice.generated_by.username],
            ["Generated On:", datetime.now().strftime("%d %b %Y at %H:%M")],
            ["Total Transactions:", str(transactions.count())],
        ]

        meta_tbl = Table(meta_data, colWidths=[120, 330])
        meta_tbl.setStyle(TableStyle([
            ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
            ('FONTNAME', (1, 0), (1, -1), 'Helvetica'),
            ('BACKGROUND', (0, 0), (0, -1), colors.HexColor('#e8eaf6')),
            ('GRID', (0, 0), (-1, -1), 0.4, colors.grey),
            ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
            ('PADDING', (0, 0), (-1, -1), 6),
        ]))
        elems.append(meta_tbl)
        elems.append(Spacer(1, 20))

        # Transactions table
        headers = ["S.No", "Transaction #", "Supplier", "Airline", "Fuel Type", "Qty (L)", "Amount (₹)"]
        
        # Adjust column widths based on content
        col_widths = [40, 90, 100, 100, 80, 70, 80]
        
        # Prepare data
        table_data = [headers]
        grand_qty = grand_amt = 0
        
        for idx, tx in enumerate(transactions, 1):
            qty = float(tx.quantity or 0)
            amt = float(tx.total_amount or 0)
            grand_qty += qty
            grand_amt += amt

            supplier_name = tx.supplier.company_name if tx.supplier else "—"
            airline_name = tx.airline.airline_name if tx.airline else "—"
            
            # Handle fuel type display
            if hasattr(tx, 'get_fuel_type_display'):
                fuel_type = tx.get_fuel_type_display()
            else:
                fuel_type = str(tx.fuel_type) if tx.fuel_type else "—"

            table_data.append([
                str(idx),
                tx.transaction_number,
                supplier_name,
                airline_name,
                fuel_type,
                f"{qty:,.2f}",
                f"{amt:,.2f}",
            ])

        # Add total row
        table_data.append([
            "", "", "", "", "TOTAL", 
            f"{grand_qty:,.2f}", 
            f"{grand_amt:,.2f}"
        ])

        # Create and style the table
        txn_tbl = Table(table_data, colWidths=col_widths, repeatRows=1)
        
        # Style the table
        table_style = [
            # Header style
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#1a237e')),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, 0), 9),
            ('ALIGN', (0, 0), (-1, 0), 'CENTER'),
            
            # Body style
            ('FONTNAME', (0, 1), (-1, -2), 'Helvetica'),
            ('FONTSIZE', (0, 1), (-1, -2), 8),
            ('ROWBACKGROUNDS', (0, 1), (-1, -2), 
             [colors.white, colors.HexColor('#f5f5f5')]),
            
            # Total row style
            ('FONTNAME', (0, -1), (-1, -1), 'Helvetica-Bold'),
            ('BACKGROUND', (0, -1), (-1, -1), colors.HexColor('#e8eaf6')),
            ('FONTSIZE', (0, -1), (-1, -1), 10),
            
            # Alignment
            ('ALIGN', (5, 1), (5, -1), 'RIGHT'),  # Quantity column
            ('ALIGN', (6, 1), (6, -1), 'RIGHT'),  # Amount column
            ('ALIGN', (0, 1), (0, -1), 'CENTER'), # S.No column
            ('ALIGN', (1, 1), (1, -1), 'CENTER'), # Transaction # column
            
            # Grid
            ('GRID', (0, 0), (-1, -1), 0.4, colors.grey),
            ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
            ('PADDING', (0, 0), (-1, -1), 5),
        ]
        
        txn_tbl.setStyle(TableStyle(table_style))
        elems.append(txn_tbl)
        elems.append(Spacer(1, 24))

        # Summary section
        summary_data = [
            ["SUMMARY", ""],
            ["Total Quantity:", f"{grand_qty:,.2f} Liters"],
            ["Total Amount:", f"₹ {grand_amt:,.2f}"],
            ["Average Price per Liter:", f"₹ {(grand_amt/grand_qty):,.2f}" if grand_qty > 0 else "N/A"],
        ]
        
        summary_tbl = Table(summary_data, colWidths=[140, 310])
        summary_tbl.setStyle(TableStyle([
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, 0), 11),
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#1a237e')),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
            ('FONTNAME', (0, 1), (0, -1), 'Helvetica-Bold'),
            ('BACKGROUND', (0, 1), (0, -1), colors.HexColor('#e8eaf6')),
            ('GRID', (0, 0), (-1, -1), 0.4, colors.grey),
            ('ALIGN', (1, 1), (1, -1), 'RIGHT'),
            ('PADDING', (0, 0), (-1, -1), 8),
        ]))
        elems.append(summary_tbl)
        elems.append(Spacer(1, 20))

        # Footer
        footer_text = """
        <para alignment="CENTER" fontSize="8" textColor="grey">
        This is a computer-generated invoice. No signature required.<br/>
        Generated by Airport Fuel Management System
        </para>
        """
        elems.append(Paragraph(footer_text, styles['Normal']))

        # Build PDF
        doc.build(elems)
        buffer.seek(0)
        
        return File(buffer, name=f'{invoice.invoice_number}.pdf')