# Generated by Django 4.2.5 on 2026-05-27 16:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('airport_name', models.CharField(max_length=200)),
                ('airport_code', models.CharField(max_length=4, unique=True)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(default='India', max_length=100)),
                ('runway_count', models.IntegerField(default=1)),
                ('fuel_storage_capacity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('current_fuel_stock', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'airports',
                'ordering': ['airport_name'],
            },
        ),
    ]
