# Generated by Django 4.2.5 on 2026-05-29 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='generated_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='transaction',
        ),
        migrations.AddField(
            model_name='invoice',
            name='report_type',
            field=models.CharField(choices=[('daily', 'Daily Report'), ('monthly', 'Monthly Report')], default='daily', max_length=20),
        ),
        migrations.AddField(
            model_name='invoice',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='suppliers.supplier'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='invoice',
            name='total_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
