# Generated by Django 5.2.14 on 2026-06-02 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='company_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='gst_number',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='suppliercontract',
            name='contract_number',
            field=models.CharField(max_length=50),
        ),
    ]
